#!/usr/bin/python

import os, sys, logging

log = logging.getLogger(__name__)

sys.path.insert(0, os.path.dirname(__file__) or '.')

PY_DIR = os.path.join(os.environ['PODSERVE_HOMEDIR'], "python")

virtenv = PY_DIR + '/virtenv/'

PY_CACHE = os.path.join(virtenv, 'lib', '2.7', 'site-packages')

os.environ['PYTHON_EGG_CACHE'] = os.path.join(PY_CACHE)
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')

from podserve import app as application, init_application
log.info('WSGI calling init_application()')
init_application()
